<?xml version="1.0" encoding="UTF-8"?>
<testng-results ignored="0" total="25" passed="0" failed="25" skipped="0">
  <reporter-output>
    <line>
      <![CDATA[Execution Started]]>
    </line>
    <line>
      <![CDATA[Test Started: testInvalidAuthorizationToken]]>
    </line>
    <line>
      <![CDATA[
testInvalidAuthorizationToken Response: 
{
    "error_id": 502,
    "error_message": "too many requests from this IP, more requests available in 19605 seconds",
    "error_name": "throttle_violation"
}]]>
    </line>
    <line>
      <![CDATA[testInvalidAuthorizationToken Response status code: 
400]]>
    </line>
    <line>
      <![CDATA[Test Failed: testInvalidAuthorizationToken]]>
    </line>
    <line>
      <![CDATA[Test Started: testInvalidDateFormat]]>
    </line>
    <line>
      <![CDATA[testInvalidDateFormat Response: {
    "error_id": 502,
    "error_message": "too many requests from this IP, more requests available in 19603 seconds",
    "error_name": "throttle_violation"
}]]>
    </line>
    <line>
      <![CDATA[testInvalidDateFormat Response status code: 400]]>
    </line>
    <line>
      <![CDATA[Test Failed: testInvalidDateFormat]]>
    </line>
    <line>
      <![CDATA[Test Started: testInvalidID]]>
    </line>
    <line>
      <![CDATA[testInvalidID Response: {
    "error_id": 502,
    "error_message": "too many requests from this IP, more requests available in 19602 seconds",
    "error_name": "throttle_violation"
}]]>
    </line>
    <line>
      <![CDATA[testInvalidID Response status code: 400]]>
    </line>
    <line>
      <![CDATA[testInvalidID Response status code check successful ]]>
    </line>
    <line>
      <![CDATA[Test Failed: testInvalidID]]>
    </line>
    <line>
      <![CDATA[Test Started: testInvalidMinParameter]]>
    </line>
    <line>
      <![CDATA[testInvalidMinParameter Response: {
    "error_id": 502,
    "error_message": "too many requests from this IP, more requests available in 19596 seconds",
    "error_name": "throttle_violation"
}]]>
    </line>
    <line>
      <![CDATA[testInvalidMinParameter Response status code: 400]]>
    </line>
    <line>
      <![CDATA[testInvalidMinParameter Response status code check successful ]]>
    </line>
    <line>
      <![CDATA[Test Failed: testInvalidMinParameter]]>
    </line>
    <line>
      <![CDATA[Test Started: testInvalidOrderParameter]]>
    </line>
    <line>
      <![CDATA[testInvalidOrderParameter Response: {
    "error_id": 502,
    "error_message": "too many requests from this IP, more requests available in 19594 seconds",
    "error_name": "throttle_violation"
}]]>
    </line>
    <line>
      <![CDATA[testInvalidOrderParameter Response status code: 400]]>
    </line>
    <line>
      <![CDATA[testInvalidOrderParameter Response status code check successful ]]>
    </line>
    <line>
      <![CDATA[Test Failed: testInvalidOrderParameter]]>
    </line>
    <line>
      <![CDATA[Test Started: testInvalidPageNumber]]>
    </line>
    <line>
      <![CDATA[testInvalidPageNumber Response: {
    "error_id": 502,
    "error_message": "too many requests from this IP, more requests available in 19592 seconds",
    "error_name": "throttle_violation"
}]]>
    </line>
    <line>
      <![CDATA[testInvalidPageNumber Response status code: 400]]>
    </line>
    <line>
      <![CDATA[testInvalidPageNumber Response status code check successful ]]>
    </line>
    <line>
      <![CDATA[Test Failed: testInvalidPageNumber]]>
    </line>
    <line>
      <![CDATA[Test Started: testInvalidPageSize]]>
    </line>
    <line>
      <![CDATA[testInvalidPageSize Response: {
    "error_id": 502,
    "error_message": "too many requests from this IP, more requests available in 19591 seconds",
    "error_name": "throttle_violation"
}]]>
    </line>
    <line>
      <![CDATA[testInvalidPageSize Response status code: 400]]>
    </line>
    <line>
      <![CDATA[Test Failed: testInvalidPageSize]]>
    </line>
    <line>
      <![CDATA[Test Started: testInvalidSortParameter]]>
    </line>
    <line>
      <![CDATA[testInvalidSortParameter Response: {
    "error_id": 502,
    "error_message": "too many requests from this IP, more requests available in 19589 seconds",
    "error_name": "throttle_violation"
}]]>
    </line>
    <line>
      <![CDATA[testInvalidSortParameter Response status code: 400]]>
    </line>
    <line>
      <![CDATA[testInvalidSortParameter Response status code check successful ]]>
    </line>
    <line>
      <![CDATA[Test Failed: testInvalidSortParameter]]>
    </line>
    <line>
      <![CDATA[Test Started: testMissingRequiredParameters]]>
    </line>
    <line>
      <![CDATA[testMissingRequiredParameters Response: {
    "error_id": 502,
    "error_message": "too many requests from this IP, more requests available in 19588 seconds",
    "error_name": "throttle_violation"
}]]>
    </line>
    <line>
      <![CDATA[testMissingRequiredParameters Response status code: 400]]>
    </line>
    <line>
      <![CDATA[testMissingRequiredParameters Schema validation successful. ]]>
    </line>
    <line>
      <![CDATA[testMissingRequiredParameters Response status code check successful ]]>
    </line>
    <line>
      <![CDATA[Test Failed: testMissingRequiredParameters]]>
    </line>
    <line>
      <![CDATA[Test Started: testValidRequest]]>
    </line>
    <line>
      <![CDATA[Test Failed: testValidRequest]]>
    </line>
    <line>
      <![CDATA[Test Started: testInvalidAuthorizationToken]]>
    </line>
    <line>
      <![CDATA[
testInvalidAuthorizationToken Response: 
{
    "error_id": 502,
    "error_message": "too many requests from this IP, more requests available in 19585 seconds",
    "error_name": "throttle_violation"
}]]>
    </line>
    <line>
      <![CDATA[testInvalidAuthorizationToken Response status code: 
400]]>
    </line>
    <line>
      <![CDATA[Test Failed: testInvalidAuthorizationToken]]>
    </line>
    <line>
      <![CDATA[Test Started: testInvalidDateFormat]]>
    </line>
    <line>
      <![CDATA[testInvalidDateFormat Response: {
    "error_id": 502,
    "error_message": "too many requests from this IP, more requests available in 19583 seconds",
    "error_name": "throttle_violation"
}]]>
    </line>
    <line>
      <![CDATA[testInvalidDateFormat Response status code: 400]]>
    </line>
    <line>
      <![CDATA[Test Failed: testInvalidDateFormat]]>
    </line>
    <line>
      <![CDATA[Test Started: testInvalidMinParameter]]>
    </line>
    <line>
      <![CDATA[testInvalidMinParameter Response: {
    "error_id": 502,
    "error_message": "too many requests from this IP, more requests available in 19582 seconds",
    "error_name": "throttle_violation"
}]]>
    </line>
    <line>
      <![CDATA[testInvalidMinParameter Response status code: 400]]>
    </line>
    <line>
      <![CDATA[testInvalidMinParameter Response status code check successful ]]>
    </line>
    <line>
      <![CDATA[Test Failed: testInvalidMinParameter]]>
    </line>
    <line>
      <![CDATA[Test Started: testInvalidOrderParameter]]>
    </line>
    <line>
      <![CDATA[testInvalidOrderParameter Response: {
    "error_id": 502,
    "error_message": "too many requests from this IP, more requests available in 19580 seconds",
    "error_name": "throttle_violation"
}]]>
    </line>
    <line>
      <![CDATA[testInvalidOrderParameter Response status code: 400]]>
    </line>
    <line>
      <![CDATA[testInvalidOrderParameter Response status code check successful ]]>
    </line>
    <line>
      <![CDATA[Test Failed: testInvalidOrderParameter]]>
    </line>
    <line>
      <![CDATA[Test Started: testInvalidPageNumber]]>
    </line>
    <line>
      <![CDATA[testInvalidPageNumber Response: {
    "error_id": 502,
    "error_message": "too many requests from this IP, more requests available in 19578 seconds",
    "error_name": "throttle_violation"
}]]>
    </line>
    <line>
      <![CDATA[testInvalidPageNumber Response status code: 400]]>
    </line>
    <line>
      <![CDATA[testInvalidPageNumber Response status code check successful ]]>
    </line>
    <line>
      <![CDATA[Test Failed: testInvalidPageNumber]]>
    </line>
    <line>
      <![CDATA[Test Started: testInvalidPageSize]]>
    </line>
    <line>
      <![CDATA[testInvalidPageSize Response: {
    "error_id": 502,
    "error_message": "too many requests from this IP, more requests available in 19577 seconds",
    "error_name": "throttle_violation"
}]]>
    </line>
    <line>
      <![CDATA[testInvalidPageSize Response status code: 400]]>
    </line>
    <line>
      <![CDATA[Test Failed: testInvalidPageSize]]>
    </line>
    <line>
      <![CDATA[Test Started: testInvalidSortParameter]]>
    </line>
    <line>
      <![CDATA[testInvalidSortParameter Response: {
    "error_id": 502,
    "error_message": "too many requests from this IP, more requests available in 19575 seconds",
    "error_name": "throttle_violation"
}]]>
    </line>
    <line>
      <![CDATA[testInvalidSortParameter Response status code: 400]]>
    </line>
    <line>
      <![CDATA[testInvalidSortParameter Response status code check successful ]]>
    </line>
    <line>
      <![CDATA[Test Failed: testInvalidSortParameter]]>
    </line>
    <line>
      <![CDATA[Test Started: testMissingRequiredParameters]]>
    </line>
    <line>
      <![CDATA[testMissingRequiredParameters Response: {
    "error_id": 502,
    "error_message": "too many requests from this IP, more requests available in 19573 seconds",
    "error_name": "throttle_violation"
}]]>
    </line>
    <line>
      <![CDATA[testMissingRequiredParameters Response status code: 400]]>
    </line>
    <line>
      <![CDATA[testMissingRequiredParameters Schema validation successful. ]]>
    </line>
    <line>
      <![CDATA[testMissingRequiredParameters Response status code check successful ]]>
    </line>
    <line>
      <![CDATA[Test Failed: testMissingRequiredParameters]]>
    </line>
    <line>
      <![CDATA[Test Started: testValidRequest]]>
    </line>
    <line>
      <![CDATA[Test Failed: testValidRequest]]>
    </line>
    <line>
      <![CDATA[Test Started: testInvalidAuthorizationToken]]>
    </line>
    <line>
      <![CDATA[
testInvalidAuthorizationToken Response: 
{
    "error_id": 502,
    "error_message": "too many requests from this IP, more requests available in 19570 seconds",
    "error_name": "throttle_violation"
}]]>
    </line>
    <line>
      <![CDATA[testInvalidAuthorizationToken Response status code: 
400]]>
    </line>
    <line>
      <![CDATA[Test Failed: testInvalidAuthorizationToken]]>
    </line>
    <line>
      <![CDATA[Test Started: testInvalidDateFormat]]>
    </line>
    <line>
      <![CDATA[testInvalidDateFormat Response: {
    "error_id": 502,
    "error_message": "too many requests from this IP, more requests available in 19569 seconds",
    "error_name": "throttle_violation"
}]]>
    </line>
    <line>
      <![CDATA[testInvalidDateFormat Response status code: 400]]>
    </line>
    <line>
      <![CDATA[Test Failed: testInvalidDateFormat]]>
    </line>
    <line>
      <![CDATA[Test Started: testInvalidPageNumber]]>
    </line>
    <line>
      <![CDATA[testInvalidPageNumber Response: {
    "error_id": 502,
    "error_message": "too many requests from this IP, more requests available in 19567 seconds",
    "error_name": "throttle_violation"
}]]>
    </line>
    <line>
      <![CDATA[testInvalidPageNumber Response status code: 400]]>
    </line>
    <line>
      <![CDATA[testInvalidPageNumber Response status code check successful ]]>
    </line>
    <line>
      <![CDATA[Test Failed: testInvalidPageNumber]]>
    </line>
    <line>
      <![CDATA[Test Started: testInvalidPageSize]]>
    </line>
    <line>
      <![CDATA[testInvalidPageSize Response: {
    "error_id": 502,
    "error_message": "too many requests from this IP, more requests available in 19565 seconds",
    "error_name": "throttle_violation"
}]]>
    </line>
    <line>
      <![CDATA[testInvalidPageSize Response status code: 400]]>
    </line>
    <line>
      <![CDATA[Test Failed: testInvalidPageSize]]>
    </line>
    <line>
      <![CDATA[Test Started: testMissingRequiredParameters]]>
    </line>
    <line>
      <![CDATA[testMissingRequiredParameters Response: {
    "error_id": 502,
    "error_message": "too many requests from this IP, more requests available in 19564 seconds",
    "error_name": "throttle_violation"
}]]>
    </line>
    <line>
      <![CDATA[testMissingRequiredParameters Response status code: 400]]>
    </line>
    <line>
      <![CDATA[testMissingRequiredParameters Schema validation successful. ]]>
    </line>
    <line>
      <![CDATA[testMissingRequiredParameters Response status code check successful ]]>
    </line>
    <line>
      <![CDATA[Test Failed: testMissingRequiredParameters]]>
    </line>
    <line>
      <![CDATA[Test Started: testValidRequest]]>
    </line>
    <line>
      <![CDATA[Test Failed: testValidRequest]]>
    </line>
  </reporter-output>
  <suite started-at="2024-02-07T22:11:40 IST" name="Suite" finished-at="2024-02-07T22:12:29 IST" duration-ms="49779">
    <groups>
    </groups>
    <test started-at="2024-02-07T22:11:40 IST" name="Test" finished-at="2024-02-07T22:12:29 IST" duration-ms="49779">
      <class name="Ollion.RestAssuredAssignment.badges_tags_GET">
        <test-method is-config="true" signature="setUp()[pri:0, instance:Ollion.RestAssuredAssignment.badges_tags_GET@487db668]" started-at="2024-02-07T22:12:06 IST" name="setUp" finished-at="2024-02-07T22:12:06 IST" duration-ms="1" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- setUp -->
        <test-method signature="testInvalidAuthorizationToken()[pri:0, instance:Ollion.RestAssuredAssignment.badges_tags_GET@487db668]" started-at="2024-02-07T22:12:06 IST" name="testInvalidAuthorizationToken" finished-at="2024-02-07T22:12:07 IST" duration-ms="1479" status="FAIL">
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[expected [200] but found [400]]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: expected [200] but found [400]
at org.testng.Assert.fail(Assert.java:111)
at org.testng.Assert.failNotEquals(Assert.java:1578)
at org.testng.Assert.assertEqualsImpl(Assert.java:150)
at org.testng.Assert.assertEquals(Assert.java:132)
at org.testng.Assert.assertEquals(Assert.java:1419)
at org.testng.Assert.assertEquals(Assert.java:1383)
at org.testng.Assert.assertEquals(Assert.java:1429)
at Ollion.RestAssuredAssignment.badges_tags_GET.testInvalidAuthorizationToken(badges_tags_GET.java:92)
at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:103)
at java.base/java.lang.reflect.Method.invoke(Method.java:580)
at org.testng.internal.invokers.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:139)
at org.testng.internal.invokers.TestInvoker.invokeMethod(TestInvoker.java:664)
at org.testng.internal.invokers.TestInvoker.invokeTestMethod(TestInvoker.java:228)
at org.testng.internal.invokers.MethodRunner.runInSequence(MethodRunner.java:63)
at org.testng.internal.invokers.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:961)
at org.testng.internal.invokers.TestInvoker.invokeTestMethods(TestInvoker.java:201)
at org.testng.internal.invokers.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:148)
at org.testng.internal.invokers.TestMethodWorker.run(TestMethodWorker.java:128)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1596)
at org.testng.TestRunner.privateRun(TestRunner.java:819)
at org.testng.TestRunner.run(TestRunner.java:619)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:443)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:437)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:397)
at org.testng.SuiteRunner.run(SuiteRunner.java:336)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:95)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1301)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1228)
at org.testng.TestNG.runSuites(TestNG.java:1134)
at org.testng.TestNG.run(TestNG.java:1101)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
            <line>
              <![CDATA[Test Started: testInvalidAuthorizationToken]]>
            </line>
            <line>
              <![CDATA[
testInvalidAuthorizationToken Response: 
{
    "error_id": 502,
    "error_message": "too many requests from this IP, more requests available in 19585 seconds",
    "error_name": "throttle_violation"
}]]>
            </line>
            <line>
              <![CDATA[testInvalidAuthorizationToken Response status code: 
400]]>
            </line>
            <line>
              <![CDATA[Test Failed: testInvalidAuthorizationToken]]>
            </line>
          </reporter-output>
        </test-method> <!-- testInvalidAuthorizationToken -->
        <test-method signature="testInvalidDateFormat()[pri:0, instance:Ollion.RestAssuredAssignment.badges_tags_GET@487db668]" started-at="2024-02-07T22:12:07 IST" name="testInvalidDateFormat" finished-at="2024-02-07T22:12:09 IST" duration-ms="1497" status="FAIL">
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[expected [200] but found [400]]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: expected [200] but found [400]
at org.testng.Assert.fail(Assert.java:111)
at org.testng.Assert.failNotEquals(Assert.java:1578)
at org.testng.Assert.assertEqualsImpl(Assert.java:150)
at org.testng.Assert.assertEquals(Assert.java:132)
at org.testng.Assert.assertEquals(Assert.java:1419)
at org.testng.Assert.assertEquals(Assert.java:1383)
at org.testng.Assert.assertEquals(Assert.java:1429)
at Ollion.RestAssuredAssignment.badges_tags_GET.testInvalidDateFormat(badges_tags_GET.java:222)
at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:103)
at java.base/java.lang.reflect.Method.invoke(Method.java:580)
at org.testng.internal.invokers.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:139)
at org.testng.internal.invokers.TestInvoker.invokeMethod(TestInvoker.java:664)
at org.testng.internal.invokers.TestInvoker.invokeTestMethod(TestInvoker.java:228)
at org.testng.internal.invokers.MethodRunner.runInSequence(MethodRunner.java:63)
at org.testng.internal.invokers.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:961)
at org.testng.internal.invokers.TestInvoker.invokeTestMethods(TestInvoker.java:201)
at org.testng.internal.invokers.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:148)
at org.testng.internal.invokers.TestMethodWorker.run(TestMethodWorker.java:128)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1596)
at org.testng.TestRunner.privateRun(TestRunner.java:819)
at org.testng.TestRunner.run(TestRunner.java:619)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:443)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:437)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:397)
at org.testng.SuiteRunner.run(SuiteRunner.java:336)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:95)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1301)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1228)
at org.testng.TestNG.runSuites(TestNG.java:1134)
at org.testng.TestNG.run(TestNG.java:1101)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
            <line>
              <![CDATA[Test Started: testInvalidDateFormat]]>
            </line>
            <line>
              <![CDATA[testInvalidDateFormat Response: {
    "error_id": 502,
    "error_message": "too many requests from this IP, more requests available in 19583 seconds",
    "error_name": "throttle_violation"
}]]>
            </line>
            <line>
              <![CDATA[testInvalidDateFormat Response status code: 400]]>
            </line>
            <line>
              <![CDATA[Test Failed: testInvalidDateFormat]]>
            </line>
          </reporter-output>
        </test-method> <!-- testInvalidDateFormat -->
        <test-method signature="testInvalidMinParameter()[pri:0, instance:Ollion.RestAssuredAssignment.badges_tags_GET@487db668]" started-at="2024-02-07T22:12:09 IST" name="testInvalidMinParameter" finished-at="2024-02-07T22:12:10 IST" duration-ms="1512" status="FAIL">
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[expected [400] but found [502]]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: expected [400] but found [502]
at org.testng.Assert.fail(Assert.java:111)
at org.testng.Assert.failNotEquals(Assert.java:1578)
at org.testng.Assert.assertEqualsImpl(Assert.java:150)
at org.testng.Assert.assertEquals(Assert.java:132)
at org.testng.Assert.assertEquals(Assert.java:1419)
at org.testng.Assert.assertEquals(Assert.java:1383)
at org.testng.Assert.assertEquals(Assert.java:1429)
at Ollion.RestAssuredAssignment.badges_tags_GET.testInvalidMinParameter(badges_tags_GET.java:256)
at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:103)
at java.base/java.lang.reflect.Method.invoke(Method.java:580)
at org.testng.internal.invokers.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:139)
at org.testng.internal.invokers.TestInvoker.invokeMethod(TestInvoker.java:664)
at org.testng.internal.invokers.TestInvoker.invokeTestMethod(TestInvoker.java:228)
at org.testng.internal.invokers.MethodRunner.runInSequence(MethodRunner.java:63)
at org.testng.internal.invokers.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:961)
at org.testng.internal.invokers.TestInvoker.invokeTestMethods(TestInvoker.java:201)
at org.testng.internal.invokers.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:148)
at org.testng.internal.invokers.TestMethodWorker.run(TestMethodWorker.java:128)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1596)
at org.testng.TestRunner.privateRun(TestRunner.java:819)
at org.testng.TestRunner.run(TestRunner.java:619)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:443)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:437)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:397)
at org.testng.SuiteRunner.run(SuiteRunner.java:336)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:95)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1301)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1228)
at org.testng.TestNG.runSuites(TestNG.java:1134)
at org.testng.TestNG.run(TestNG.java:1101)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
            <line>
              <![CDATA[Test Started: testInvalidMinParameter]]>
            </line>
            <line>
              <![CDATA[testInvalidMinParameter Response: {
    "error_id": 502,
    "error_message": "too many requests from this IP, more requests available in 19582 seconds",
    "error_name": "throttle_violation"
}]]>
            </line>
            <line>
              <![CDATA[testInvalidMinParameter Response status code: 400]]>
            </line>
            <line>
              <![CDATA[testInvalidMinParameter Response status code check successful ]]>
            </line>
            <line>
              <![CDATA[Test Failed: testInvalidMinParameter]]>
            </line>
          </reporter-output>
        </test-method> <!-- testInvalidMinParameter -->
        <test-method signature="testInvalidOrderParameter()[pri:0, instance:Ollion.RestAssuredAssignment.badges_tags_GET@487db668]" started-at="2024-02-07T22:12:10 IST" name="testInvalidOrderParameter" finished-at="2024-02-07T22:12:12 IST" duration-ms="1792" status="FAIL">
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[expected [400] but found [502]]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: expected [400] but found [502]
at org.testng.Assert.fail(Assert.java:111)
at org.testng.Assert.failNotEquals(Assert.java:1578)
at org.testng.Assert.assertEqualsImpl(Assert.java:150)
at org.testng.Assert.assertEquals(Assert.java:132)
at org.testng.Assert.assertEquals(Assert.java:1419)
at org.testng.Assert.assertEquals(Assert.java:1383)
at org.testng.Assert.assertEquals(Assert.java:1429)
at Ollion.RestAssuredAssignment.badges_tags_GET.testInvalidOrderParameter(badges_tags_GET.java:191)
at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:103)
at java.base/java.lang.reflect.Method.invoke(Method.java:580)
at org.testng.internal.invokers.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:139)
at org.testng.internal.invokers.TestInvoker.invokeMethod(TestInvoker.java:664)
at org.testng.internal.invokers.TestInvoker.invokeTestMethod(TestInvoker.java:228)
at org.testng.internal.invokers.MethodRunner.runInSequence(MethodRunner.java:63)
at org.testng.internal.invokers.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:961)
at org.testng.internal.invokers.TestInvoker.invokeTestMethods(TestInvoker.java:201)
at org.testng.internal.invokers.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:148)
at org.testng.internal.invokers.TestMethodWorker.run(TestMethodWorker.java:128)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1596)
at org.testng.TestRunner.privateRun(TestRunner.java:819)
at org.testng.TestRunner.run(TestRunner.java:619)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:443)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:437)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:397)
at org.testng.SuiteRunner.run(SuiteRunner.java:336)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:95)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1301)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1228)
at org.testng.TestNG.runSuites(TestNG.java:1134)
at org.testng.TestNG.run(TestNG.java:1101)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
            <line>
              <![CDATA[Test Started: testInvalidOrderParameter]]>
            </line>
            <line>
              <![CDATA[testInvalidOrderParameter Response: {
    "error_id": 502,
    "error_message": "too many requests from this IP, more requests available in 19580 seconds",
    "error_name": "throttle_violation"
}]]>
            </line>
            <line>
              <![CDATA[testInvalidOrderParameter Response status code: 400]]>
            </line>
            <line>
              <![CDATA[testInvalidOrderParameter Response status code check successful ]]>
            </line>
            <line>
              <![CDATA[Test Failed: testInvalidOrderParameter]]>
            </line>
          </reporter-output>
        </test-method> <!-- testInvalidOrderParameter -->
        <test-method signature="testInvalidPageNumber()[pri:0, instance:Ollion.RestAssuredAssignment.badges_tags_GET@487db668]" started-at="2024-02-07T22:12:12 IST" name="testInvalidPageNumber" finished-at="2024-02-07T22:12:13 IST" duration-ms="1527" status="FAIL">
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[expected [400] but found [502]]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: expected [400] but found [502]
at org.testng.Assert.fail(Assert.java:111)
at org.testng.Assert.failNotEquals(Assert.java:1578)
at org.testng.Assert.assertEqualsImpl(Assert.java:150)
at org.testng.Assert.assertEquals(Assert.java:132)
at org.testng.Assert.assertEquals(Assert.java:1419)
at org.testng.Assert.assertEquals(Assert.java:1383)
at org.testng.Assert.assertEquals(Assert.java:1429)
at Ollion.RestAssuredAssignment.badges_tags_GET.testInvalidPageNumber(badges_tags_GET.java:126)
at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:103)
at java.base/java.lang.reflect.Method.invoke(Method.java:580)
at org.testng.internal.invokers.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:139)
at org.testng.internal.invokers.TestInvoker.invokeMethod(TestInvoker.java:664)
at org.testng.internal.invokers.TestInvoker.invokeTestMethod(TestInvoker.java:228)
at org.testng.internal.invokers.MethodRunner.runInSequence(MethodRunner.java:63)
at org.testng.internal.invokers.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:961)
at org.testng.internal.invokers.TestInvoker.invokeTestMethods(TestInvoker.java:201)
at org.testng.internal.invokers.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:148)
at org.testng.internal.invokers.TestMethodWorker.run(TestMethodWorker.java:128)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1596)
at org.testng.TestRunner.privateRun(TestRunner.java:819)
at org.testng.TestRunner.run(TestRunner.java:619)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:443)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:437)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:397)
at org.testng.SuiteRunner.run(SuiteRunner.java:336)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:95)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1301)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1228)
at org.testng.TestNG.runSuites(TestNG.java:1134)
at org.testng.TestNG.run(TestNG.java:1101)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
            <line>
              <![CDATA[Test Started: testInvalidPageNumber]]>
            </line>
            <line>
              <![CDATA[testInvalidPageNumber Response: {
    "error_id": 502,
    "error_message": "too many requests from this IP, more requests available in 19578 seconds",
    "error_name": "throttle_violation"
}]]>
            </line>
            <line>
              <![CDATA[testInvalidPageNumber Response status code: 400]]>
            </line>
            <line>
              <![CDATA[testInvalidPageNumber Response status code check successful ]]>
            </line>
            <line>
              <![CDATA[Test Failed: testInvalidPageNumber]]>
            </line>
          </reporter-output>
        </test-method> <!-- testInvalidPageNumber -->
        <test-method signature="testInvalidPageSize()[pri:0, instance:Ollion.RestAssuredAssignment.badges_tags_GET@487db668]" started-at="2024-02-07T22:12:13 IST" name="testInvalidPageSize" finished-at="2024-02-07T22:12:15 IST" duration-ms="1809" status="FAIL">
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[expected [200] but found [400]]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: expected [200] but found [400]
at org.testng.Assert.fail(Assert.java:111)
at org.testng.Assert.failNotEquals(Assert.java:1578)
at org.testng.Assert.assertEqualsImpl(Assert.java:150)
at org.testng.Assert.assertEquals(Assert.java:132)
at org.testng.Assert.assertEquals(Assert.java:1419)
at org.testng.Assert.assertEquals(Assert.java:1383)
at org.testng.Assert.assertEquals(Assert.java:1429)
at Ollion.RestAssuredAssignment.badges_tags_GET.testInvalidPageSize(badges_tags_GET.java:157)
at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:103)
at java.base/java.lang.reflect.Method.invoke(Method.java:580)
at org.testng.internal.invokers.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:139)
at org.testng.internal.invokers.TestInvoker.invokeMethod(TestInvoker.java:664)
at org.testng.internal.invokers.TestInvoker.invokeTestMethod(TestInvoker.java:228)
at org.testng.internal.invokers.MethodRunner.runInSequence(MethodRunner.java:63)
at org.testng.internal.invokers.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:961)
at org.testng.internal.invokers.TestInvoker.invokeTestMethods(TestInvoker.java:201)
at org.testng.internal.invokers.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:148)
at org.testng.internal.invokers.TestMethodWorker.run(TestMethodWorker.java:128)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1596)
at org.testng.TestRunner.privateRun(TestRunner.java:819)
at org.testng.TestRunner.run(TestRunner.java:619)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:443)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:437)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:397)
at org.testng.SuiteRunner.run(SuiteRunner.java:336)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:95)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1301)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1228)
at org.testng.TestNG.runSuites(TestNG.java:1134)
at org.testng.TestNG.run(TestNG.java:1101)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
            <line>
              <![CDATA[Test Started: testInvalidPageSize]]>
            </line>
            <line>
              <![CDATA[testInvalidPageSize Response: {
    "error_id": 502,
    "error_message": "too many requests from this IP, more requests available in 19577 seconds",
    "error_name": "throttle_violation"
}]]>
            </line>
            <line>
              <![CDATA[testInvalidPageSize Response status code: 400]]>
            </line>
            <line>
              <![CDATA[Test Failed: testInvalidPageSize]]>
            </line>
          </reporter-output>
        </test-method> <!-- testInvalidPageSize -->
        <test-method signature="testInvalidSortParameter()[pri:0, instance:Ollion.RestAssuredAssignment.badges_tags_GET@487db668]" started-at="2024-02-07T22:12:15 IST" name="testInvalidSortParameter" finished-at="2024-02-07T22:12:17 IST" duration-ms="1627" status="FAIL">
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[expected [400] but found [502]]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: expected [400] but found [502]
at org.testng.Assert.fail(Assert.java:111)
at org.testng.Assert.failNotEquals(Assert.java:1578)
at org.testng.Assert.assertEqualsImpl(Assert.java:150)
at org.testng.Assert.assertEquals(Assert.java:132)
at org.testng.Assert.assertEquals(Assert.java:1419)
at org.testng.Assert.assertEquals(Assert.java:1383)
at org.testng.Assert.assertEquals(Assert.java:1429)
at Ollion.RestAssuredAssignment.badges_tags_GET.testInvalidSortParameter(badges_tags_GET.java:291)
at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:103)
at java.base/java.lang.reflect.Method.invoke(Method.java:580)
at org.testng.internal.invokers.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:139)
at org.testng.internal.invokers.TestInvoker.invokeMethod(TestInvoker.java:664)
at org.testng.internal.invokers.TestInvoker.invokeTestMethod(TestInvoker.java:228)
at org.testng.internal.invokers.MethodRunner.runInSequence(MethodRunner.java:63)
at org.testng.internal.invokers.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:961)
at org.testng.internal.invokers.TestInvoker.invokeTestMethods(TestInvoker.java:201)
at org.testng.internal.invokers.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:148)
at org.testng.internal.invokers.TestMethodWorker.run(TestMethodWorker.java:128)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1596)
at org.testng.TestRunner.privateRun(TestRunner.java:819)
at org.testng.TestRunner.run(TestRunner.java:619)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:443)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:437)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:397)
at org.testng.SuiteRunner.run(SuiteRunner.java:336)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:95)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1301)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1228)
at org.testng.TestNG.runSuites(TestNG.java:1134)
at org.testng.TestNG.run(TestNG.java:1101)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
            <line>
              <![CDATA[Test Started: testInvalidSortParameter]]>
            </line>
            <line>
              <![CDATA[testInvalidSortParameter Response: {
    "error_id": 502,
    "error_message": "too many requests from this IP, more requests available in 19575 seconds",
    "error_name": "throttle_violation"
}]]>
            </line>
            <line>
              <![CDATA[testInvalidSortParameter Response status code: 400]]>
            </line>
            <line>
              <![CDATA[testInvalidSortParameter Response status code check successful ]]>
            </line>
            <line>
              <![CDATA[Test Failed: testInvalidSortParameter]]>
            </line>
          </reporter-output>
        </test-method> <!-- testInvalidSortParameter -->
        <test-method signature="testMissingRequiredParameters()[pri:0, instance:Ollion.RestAssuredAssignment.badges_tags_GET@487db668]" started-at="2024-02-07T22:12:17 IST" name="testMissingRequiredParameters" finished-at="2024-02-07T22:12:18 IST" duration-ms="1514" status="FAIL">
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[expected [400] but found [502]]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: expected [400] but found [502]
at org.testng.Assert.fail(Assert.java:111)
at org.testng.Assert.failNotEquals(Assert.java:1578)
at org.testng.Assert.assertEqualsImpl(Assert.java:150)
at org.testng.Assert.assertEquals(Assert.java:132)
at org.testng.Assert.assertEquals(Assert.java:1419)
at org.testng.Assert.assertEquals(Assert.java:1383)
at org.testng.Assert.assertEquals(Assert.java:1429)
at Ollion.RestAssuredAssignment.badges_tags_GET.testMissingRequiredParameters(badges_tags_GET.java:318)
at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:103)
at java.base/java.lang.reflect.Method.invoke(Method.java:580)
at org.testng.internal.invokers.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:139)
at org.testng.internal.invokers.TestInvoker.invokeMethod(TestInvoker.java:664)
at org.testng.internal.invokers.TestInvoker.invokeTestMethod(TestInvoker.java:228)
at org.testng.internal.invokers.MethodRunner.runInSequence(MethodRunner.java:63)
at org.testng.internal.invokers.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:961)
at org.testng.internal.invokers.TestInvoker.invokeTestMethods(TestInvoker.java:201)
at org.testng.internal.invokers.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:148)
at org.testng.internal.invokers.TestMethodWorker.run(TestMethodWorker.java:128)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1596)
at org.testng.TestRunner.privateRun(TestRunner.java:819)
at org.testng.TestRunner.run(TestRunner.java:619)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:443)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:437)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:397)
at org.testng.SuiteRunner.run(SuiteRunner.java:336)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:95)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1301)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1228)
at org.testng.TestNG.runSuites(TestNG.java:1134)
at org.testng.TestNG.run(TestNG.java:1101)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
            <line>
              <![CDATA[Test Started: testMissingRequiredParameters]]>
            </line>
            <line>
              <![CDATA[testMissingRequiredParameters Response: {
    "error_id": 502,
    "error_message": "too many requests from this IP, more requests available in 19573 seconds",
    "error_name": "throttle_violation"
}]]>
            </line>
            <line>
              <![CDATA[testMissingRequiredParameters Response status code: 400]]>
            </line>
            <line>
              <![CDATA[testMissingRequiredParameters Schema validation successful. ]]>
            </line>
            <line>
              <![CDATA[testMissingRequiredParameters Response status code check successful ]]>
            </line>
            <line>
              <![CDATA[Test Failed: testMissingRequiredParameters]]>
            </line>
          </reporter-output>
        </test-method> <!-- testMissingRequiredParameters -->
        <test-method signature="testValidRequest()[pri:0, instance:Ollion.RestAssuredAssignment.badges_tags_GET@487db668]" started-at="2024-02-07T22:12:18 IST" name="testValidRequest" finished-at="2024-02-07T22:12:20 IST" duration-ms="1456" status="FAIL">
          <exception class="java.lang.IllegalArgumentException">
            <message>
              <![CDATA[Schema to use cannot be null]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.IllegalArgumentException: Schema to use cannot be null
at io.restassured.module.jsv.JsonSchemaValidator.validateSchemaIsNotNull(JsonSchemaValidator.java:270)
at io.restassured.module.jsv.JsonSchemaValidator.access$300(JsonSchemaValidator.java:75)
at io.restassured.module.jsv.JsonSchemaValidator$JsonSchemaValidatorFactory.create(JsonSchemaValidator.java:281)
at io.restassured.module.jsv.JsonSchemaValidator.matchesJsonSchema(JsonSchemaValidator.java:166)
at io.restassured.module.jsv.JsonSchemaValidator.matchesJsonSchemaInClasspath(JsonSchemaValidator.java:117)
at Ollion.RestAssuredAssignment.badges_tags_GET.testValidRequest(badges_tags_GET.java:47)
at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:103)
at java.base/java.lang.reflect.Method.invoke(Method.java:580)
at org.testng.internal.invokers.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:139)
at org.testng.internal.invokers.TestInvoker.invokeMethod(TestInvoker.java:664)
at org.testng.internal.invokers.TestInvoker.invokeTestMethod(TestInvoker.java:228)
at org.testng.internal.invokers.MethodRunner.runInSequence(MethodRunner.java:63)
at org.testng.internal.invokers.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:961)
at org.testng.internal.invokers.TestInvoker.invokeTestMethods(TestInvoker.java:201)
at org.testng.internal.invokers.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:148)
at org.testng.internal.invokers.TestMethodWorker.run(TestMethodWorker.java:128)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1596)
at org.testng.TestRunner.privateRun(TestRunner.java:819)
at org.testng.TestRunner.run(TestRunner.java:619)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:443)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:437)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:397)
at org.testng.SuiteRunner.run(SuiteRunner.java:336)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:95)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1301)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1228)
at org.testng.TestNG.runSuites(TestNG.java:1134)
at org.testng.TestNG.run(TestNG.java:1101)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.IllegalArgumentException -->
          <reporter-output>
            <line>
              <![CDATA[Test Started: testValidRequest]]>
            </line>
            <line>
              <![CDATA[Test Failed: testValidRequest]]>
            </line>
          </reporter-output>
        </test-method> <!-- testValidRequest -->
      </class> <!-- Ollion.RestAssuredAssignment.badges_tags_GET -->
      <class name="Ollion.RestAssuredAssignment.badges_Recipients_GET">
        <test-method is-config="true" signature="setUp()[pri:0, instance:Ollion.RestAssuredAssignment.badges_Recipients_GET@46944ca9]" started-at="2024-02-07T22:12:20 IST" name="setUp" finished-at="2024-02-07T22:12:20 IST" duration-ms="1" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- setUp -->
        <test-method signature="testInvalidAuthorizationToken()[pri:0, instance:Ollion.RestAssuredAssignment.badges_Recipients_GET@46944ca9]" started-at="2024-02-07T22:12:20 IST" name="testInvalidAuthorizationToken" finished-at="2024-02-07T22:12:21 IST" duration-ms="1460" status="FAIL">
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[expected [200] but found [400]]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: expected [200] but found [400]
at org.testng.Assert.fail(Assert.java:111)
at org.testng.Assert.failNotEquals(Assert.java:1578)
at org.testng.Assert.assertEqualsImpl(Assert.java:150)
at org.testng.Assert.assertEquals(Assert.java:132)
at org.testng.Assert.assertEquals(Assert.java:1419)
at org.testng.Assert.assertEquals(Assert.java:1383)
at org.testng.Assert.assertEquals(Assert.java:1429)
at Ollion.RestAssuredAssignment.badges_Recipients_GET.testInvalidAuthorizationToken(badges_Recipients_GET.java:81)
at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:103)
at java.base/java.lang.reflect.Method.invoke(Method.java:580)
at org.testng.internal.invokers.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:139)
at org.testng.internal.invokers.TestInvoker.invokeMethod(TestInvoker.java:664)
at org.testng.internal.invokers.TestInvoker.invokeTestMethod(TestInvoker.java:228)
at org.testng.internal.invokers.MethodRunner.runInSequence(MethodRunner.java:63)
at org.testng.internal.invokers.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:961)
at org.testng.internal.invokers.TestInvoker.invokeTestMethods(TestInvoker.java:201)
at org.testng.internal.invokers.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:148)
at org.testng.internal.invokers.TestMethodWorker.run(TestMethodWorker.java:128)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1596)
at org.testng.TestRunner.privateRun(TestRunner.java:819)
at org.testng.TestRunner.run(TestRunner.java:619)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:443)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:437)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:397)
at org.testng.SuiteRunner.run(SuiteRunner.java:336)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:95)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1301)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1228)
at org.testng.TestNG.runSuites(TestNG.java:1134)
at org.testng.TestNG.run(TestNG.java:1101)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
            <line>
              <![CDATA[Test Started: testInvalidAuthorizationToken]]>
            </line>
            <line>
              <![CDATA[
testInvalidAuthorizationToken Response: 
{
    "error_id": 502,
    "error_message": "too many requests from this IP, more requests available in 19570 seconds",
    "error_name": "throttle_violation"
}]]>
            </line>
            <line>
              <![CDATA[testInvalidAuthorizationToken Response status code: 
400]]>
            </line>
            <line>
              <![CDATA[Test Failed: testInvalidAuthorizationToken]]>
            </line>
          </reporter-output>
        </test-method> <!-- testInvalidAuthorizationToken -->
        <test-method signature="testInvalidDateFormat()[pri:0, instance:Ollion.RestAssuredAssignment.badges_Recipients_GET@46944ca9]" started-at="2024-02-07T22:12:21 IST" name="testInvalidDateFormat" finished-at="2024-02-07T22:12:23 IST" duration-ms="1652" status="FAIL">
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[expected [200] but found [400]]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: expected [200] but found [400]
at org.testng.Assert.fail(Assert.java:111)
at org.testng.Assert.failNotEquals(Assert.java:1578)
at org.testng.Assert.assertEqualsImpl(Assert.java:150)
at org.testng.Assert.assertEquals(Assert.java:132)
at org.testng.Assert.assertEquals(Assert.java:1419)
at org.testng.Assert.assertEquals(Assert.java:1383)
at org.testng.Assert.assertEquals(Assert.java:1429)
at Ollion.RestAssuredAssignment.badges_Recipients_GET.testInvalidDateFormat(badges_Recipients_GET.java:164)
at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:103)
at java.base/java.lang.reflect.Method.invoke(Method.java:580)
at org.testng.internal.invokers.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:139)
at org.testng.internal.invokers.TestInvoker.invokeMethod(TestInvoker.java:664)
at org.testng.internal.invokers.TestInvoker.invokeTestMethod(TestInvoker.java:228)
at org.testng.internal.invokers.MethodRunner.runInSequence(MethodRunner.java:63)
at org.testng.internal.invokers.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:961)
at org.testng.internal.invokers.TestInvoker.invokeTestMethods(TestInvoker.java:201)
at org.testng.internal.invokers.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:148)
at org.testng.internal.invokers.TestMethodWorker.run(TestMethodWorker.java:128)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1596)
at org.testng.TestRunner.privateRun(TestRunner.java:819)
at org.testng.TestRunner.run(TestRunner.java:619)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:443)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:437)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:397)
at org.testng.SuiteRunner.run(SuiteRunner.java:336)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:95)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1301)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1228)
at org.testng.TestNG.runSuites(TestNG.java:1134)
at org.testng.TestNG.run(TestNG.java:1101)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
            <line>
              <![CDATA[Test Started: testInvalidDateFormat]]>
            </line>
            <line>
              <![CDATA[testInvalidDateFormat Response: {
    "error_id": 502,
    "error_message": "too many requests from this IP, more requests available in 19569 seconds",
    "error_name": "throttle_violation"
}]]>
            </line>
            <line>
              <![CDATA[testInvalidDateFormat Response status code: 400]]>
            </line>
            <line>
              <![CDATA[Test Failed: testInvalidDateFormat]]>
            </line>
          </reporter-output>
        </test-method> <!-- testInvalidDateFormat -->
        <test-method signature="testInvalidPageNumber()[pri:0, instance:Ollion.RestAssuredAssignment.badges_Recipients_GET@46944ca9]" started-at="2024-02-07T22:12:23 IST" name="testInvalidPageNumber" finished-at="2024-02-07T22:12:25 IST" duration-ms="1586" status="FAIL">
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[expected [400] but found [502]]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: expected [400] but found [502]
at org.testng.Assert.fail(Assert.java:111)
at org.testng.Assert.failNotEquals(Assert.java:1578)
at org.testng.Assert.assertEqualsImpl(Assert.java:150)
at org.testng.Assert.assertEquals(Assert.java:132)
at org.testng.Assert.assertEquals(Assert.java:1419)
at org.testng.Assert.assertEquals(Assert.java:1383)
at org.testng.Assert.assertEquals(Assert.java:1429)
at Ollion.RestAssuredAssignment.badges_Recipients_GET.testInvalidPageNumber(badges_Recipients_GET.java:111)
at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:103)
at java.base/java.lang.reflect.Method.invoke(Method.java:580)
at org.testng.internal.invokers.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:139)
at org.testng.internal.invokers.TestInvoker.invokeMethod(TestInvoker.java:664)
at org.testng.internal.invokers.TestInvoker.invokeTestMethod(TestInvoker.java:228)
at org.testng.internal.invokers.MethodRunner.runInSequence(MethodRunner.java:63)
at org.testng.internal.invokers.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:961)
at org.testng.internal.invokers.TestInvoker.invokeTestMethods(TestInvoker.java:201)
at org.testng.internal.invokers.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:148)
at org.testng.internal.invokers.TestMethodWorker.run(TestMethodWorker.java:128)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1596)
at org.testng.TestRunner.privateRun(TestRunner.java:819)
at org.testng.TestRunner.run(TestRunner.java:619)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:443)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:437)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:397)
at org.testng.SuiteRunner.run(SuiteRunner.java:336)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:95)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1301)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1228)
at org.testng.TestNG.runSuites(TestNG.java:1134)
at org.testng.TestNG.run(TestNG.java:1101)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
            <line>
              <![CDATA[Test Started: testInvalidPageNumber]]>
            </line>
            <line>
              <![CDATA[testInvalidPageNumber Response: {
    "error_id": 502,
    "error_message": "too many requests from this IP, more requests available in 19567 seconds",
    "error_name": "throttle_violation"
}]]>
            </line>
            <line>
              <![CDATA[testInvalidPageNumber Response status code: 400]]>
            </line>
            <line>
              <![CDATA[testInvalidPageNumber Response status code check successful ]]>
            </line>
            <line>
              <![CDATA[Test Failed: testInvalidPageNumber]]>
            </line>
          </reporter-output>
        </test-method> <!-- testInvalidPageNumber -->
        <test-method signature="testInvalidPageSize()[pri:0, instance:Ollion.RestAssuredAssignment.badges_Recipients_GET@46944ca9]" started-at="2024-02-07T22:12:25 IST" name="testInvalidPageSize" finished-at="2024-02-07T22:12:26 IST" duration-ms="1833" status="FAIL">
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[expected [200] but found [400]]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: expected [200] but found [400]
at org.testng.Assert.fail(Assert.java:111)
at org.testng.Assert.failNotEquals(Assert.java:1578)
at org.testng.Assert.assertEqualsImpl(Assert.java:150)
at org.testng.Assert.assertEquals(Assert.java:132)
at org.testng.Assert.assertEquals(Assert.java:1419)
at org.testng.Assert.assertEquals(Assert.java:1383)
at org.testng.Assert.assertEquals(Assert.java:1429)
at Ollion.RestAssuredAssignment.badges_Recipients_GET.testInvalidPageSize(badges_Recipients_GET.java:138)
at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:103)
at java.base/java.lang.reflect.Method.invoke(Method.java:580)
at org.testng.internal.invokers.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:139)
at org.testng.internal.invokers.TestInvoker.invokeMethod(TestInvoker.java:664)
at org.testng.internal.invokers.TestInvoker.invokeTestMethod(TestInvoker.java:228)
at org.testng.internal.invokers.MethodRunner.runInSequence(MethodRunner.java:63)
at org.testng.internal.invokers.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:961)
at org.testng.internal.invokers.TestInvoker.invokeTestMethods(TestInvoker.java:201)
at org.testng.internal.invokers.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:148)
at org.testng.internal.invokers.TestMethodWorker.run(TestMethodWorker.java:128)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1596)
at org.testng.TestRunner.privateRun(TestRunner.java:819)
at org.testng.TestRunner.run(TestRunner.java:619)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:443)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:437)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:397)
at org.testng.SuiteRunner.run(SuiteRunner.java:336)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:95)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1301)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1228)
at org.testng.TestNG.runSuites(TestNG.java:1134)
at org.testng.TestNG.run(TestNG.java:1101)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
            <line>
              <![CDATA[Test Started: testInvalidPageSize]]>
            </line>
            <line>
              <![CDATA[testInvalidPageSize Response: {
    "error_id": 502,
    "error_message": "too many requests from this IP, more requests available in 19565 seconds",
    "error_name": "throttle_violation"
}]]>
            </line>
            <line>
              <![CDATA[testInvalidPageSize Response status code: 400]]>
            </line>
            <line>
              <![CDATA[Test Failed: testInvalidPageSize]]>
            </line>
          </reporter-output>
        </test-method> <!-- testInvalidPageSize -->
        <test-method signature="testMissingRequiredParameters()[pri:0, instance:Ollion.RestAssuredAssignment.badges_Recipients_GET@46944ca9]" started-at="2024-02-07T22:12:26 IST" name="testMissingRequiredParameters" finished-at="2024-02-07T22:12:28 IST" duration-ms="1533" status="FAIL">
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[expected [400] but found [502]]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: expected [400] but found [502]
at org.testng.Assert.fail(Assert.java:111)
at org.testng.Assert.failNotEquals(Assert.java:1578)
at org.testng.Assert.assertEqualsImpl(Assert.java:150)
at org.testng.Assert.assertEquals(Assert.java:132)
at org.testng.Assert.assertEquals(Assert.java:1419)
at org.testng.Assert.assertEquals(Assert.java:1383)
at org.testng.Assert.assertEquals(Assert.java:1429)
at Ollion.RestAssuredAssignment.badges_Recipients_GET.testMissingRequiredParameters(badges_Recipients_GET.java:190)
at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:103)
at java.base/java.lang.reflect.Method.invoke(Method.java:580)
at org.testng.internal.invokers.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:139)
at org.testng.internal.invokers.TestInvoker.invokeMethod(TestInvoker.java:664)
at org.testng.internal.invokers.TestInvoker.invokeTestMethod(TestInvoker.java:228)
at org.testng.internal.invokers.MethodRunner.runInSequence(MethodRunner.java:63)
at org.testng.internal.invokers.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:961)
at org.testng.internal.invokers.TestInvoker.invokeTestMethods(TestInvoker.java:201)
at org.testng.internal.invokers.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:148)
at org.testng.internal.invokers.TestMethodWorker.run(TestMethodWorker.java:128)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1596)
at org.testng.TestRunner.privateRun(TestRunner.java:819)
at org.testng.TestRunner.run(TestRunner.java:619)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:443)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:437)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:397)
at org.testng.SuiteRunner.run(SuiteRunner.java:336)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:95)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1301)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1228)
at org.testng.TestNG.runSuites(TestNG.java:1134)
at org.testng.TestNG.run(TestNG.java:1101)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
            <line>
              <![CDATA[Test Started: testMissingRequiredParameters]]>
            </line>
            <line>
              <![CDATA[testMissingRequiredParameters Response: {
    "error_id": 502,
    "error_message": "too many requests from this IP, more requests available in 19564 seconds",
    "error_name": "throttle_violation"
}]]>
            </line>
            <line>
              <![CDATA[testMissingRequiredParameters Response status code: 400]]>
            </line>
            <line>
              <![CDATA[testMissingRequiredParameters Schema validation successful. ]]>
            </line>
            <line>
              <![CDATA[testMissingRequiredParameters Response status code check successful ]]>
            </line>
            <line>
              <![CDATA[Test Failed: testMissingRequiredParameters]]>
            </line>
          </reporter-output>
        </test-method> <!-- testMissingRequiredParameters -->
        <test-method signature="testValidRequest()[pri:0, instance:Ollion.RestAssuredAssignment.badges_Recipients_GET@46944ca9]" started-at="2024-02-07T22:12:28 IST" name="testValidRequest" finished-at="2024-02-07T22:12:29 IST" duration-ms="1497" status="FAIL">
          <exception class="java.lang.IllegalArgumentException">
            <message>
              <![CDATA[Schema to use cannot be null]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.IllegalArgumentException: Schema to use cannot be null
at io.restassured.module.jsv.JsonSchemaValidator.validateSchemaIsNotNull(JsonSchemaValidator.java:270)
at io.restassured.module.jsv.JsonSchemaValidator.access$300(JsonSchemaValidator.java:75)
at io.restassured.module.jsv.JsonSchemaValidator$JsonSchemaValidatorFactory.create(JsonSchemaValidator.java:281)
at io.restassured.module.jsv.JsonSchemaValidator.matchesJsonSchema(JsonSchemaValidator.java:166)
at io.restassured.module.jsv.JsonSchemaValidator.matchesJsonSchemaInClasspath(JsonSchemaValidator.java:117)
at Ollion.RestAssuredAssignment.badges_Recipients_GET.testValidRequest(badges_Recipients_GET.java:43)
at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:103)
at java.base/java.lang.reflect.Method.invoke(Method.java:580)
at org.testng.internal.invokers.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:139)
at org.testng.internal.invokers.TestInvoker.invokeMethod(TestInvoker.java:664)
at org.testng.internal.invokers.TestInvoker.invokeTestMethod(TestInvoker.java:228)
at org.testng.internal.invokers.MethodRunner.runInSequence(MethodRunner.java:63)
at org.testng.internal.invokers.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:961)
at org.testng.internal.invokers.TestInvoker.invokeTestMethods(TestInvoker.java:201)
at org.testng.internal.invokers.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:148)
at org.testng.internal.invokers.TestMethodWorker.run(TestMethodWorker.java:128)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1596)
at org.testng.TestRunner.privateRun(TestRunner.java:819)
at org.testng.TestRunner.run(TestRunner.java:619)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:443)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:437)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:397)
at org.testng.SuiteRunner.run(SuiteRunner.java:336)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:95)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1301)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1228)
at org.testng.TestNG.runSuites(TestNG.java:1134)
at org.testng.TestNG.run(TestNG.java:1101)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.IllegalArgumentException -->
          <reporter-output>
            <line>
              <![CDATA[Test Started: testValidRequest]]>
            </line>
            <line>
              <![CDATA[Test Failed: testValidRequest]]>
            </line>
          </reporter-output>
        </test-method> <!-- testValidRequest -->
      </class> <!-- Ollion.RestAssuredAssignment.badges_Recipients_GET -->
      <class name="Ollion.RestAssuredAssignment.badges_ids_GET">
        <test-method is-config="true" signature="setUp()[pri:0, instance:Ollion.RestAssuredAssignment.badges_ids_GET@2e2ff723]" started-at="2024-02-07T22:11:40 IST" name="setUp" finished-at="2024-02-07T22:11:41 IST" duration-ms="1279" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- setUp -->
        <test-method signature="testInvalidAuthorizationToken()[pri:0, instance:Ollion.RestAssuredAssignment.badges_ids_GET@2e2ff723]" started-at="2024-02-07T22:11:41 IST" name="testInvalidAuthorizationToken" finished-at="2024-02-07T22:11:47 IST" duration-ms="6176" status="FAIL">
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[expected [200] but found [400]]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: expected [200] but found [400]
at org.testng.Assert.fail(Assert.java:111)
at org.testng.Assert.failNotEquals(Assert.java:1578)
at org.testng.Assert.assertEqualsImpl(Assert.java:150)
at org.testng.Assert.assertEquals(Assert.java:132)
at org.testng.Assert.assertEquals(Assert.java:1419)
at org.testng.Assert.assertEquals(Assert.java:1383)
at org.testng.Assert.assertEquals(Assert.java:1429)
at Ollion.RestAssuredAssignment.badges_ids_GET.testInvalidAuthorizationToken(badges_ids_GET.java:87)
at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:103)
at java.base/java.lang.reflect.Method.invoke(Method.java:580)
at org.testng.internal.invokers.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:139)
at org.testng.internal.invokers.TestInvoker.invokeMethod(TestInvoker.java:664)
at org.testng.internal.invokers.TestInvoker.invokeTestMethod(TestInvoker.java:228)
at org.testng.internal.invokers.MethodRunner.runInSequence(MethodRunner.java:63)
at org.testng.internal.invokers.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:961)
at org.testng.internal.invokers.TestInvoker.invokeTestMethods(TestInvoker.java:201)
at org.testng.internal.invokers.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:148)
at org.testng.internal.invokers.TestMethodWorker.run(TestMethodWorker.java:128)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1596)
at org.testng.TestRunner.privateRun(TestRunner.java:819)
at org.testng.TestRunner.run(TestRunner.java:619)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:443)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:437)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:397)
at org.testng.SuiteRunner.run(SuiteRunner.java:336)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:95)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1301)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1228)
at org.testng.TestNG.runSuites(TestNG.java:1134)
at org.testng.TestNG.run(TestNG.java:1101)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
            <line>
              <![CDATA[Test Started: testInvalidAuthorizationToken]]>
            </line>
            <line>
              <![CDATA[
testInvalidAuthorizationToken Response: 
{
    "error_id": 502,
    "error_message": "too many requests from this IP, more requests available in 19605 seconds",
    "error_name": "throttle_violation"
}]]>
            </line>
            <line>
              <![CDATA[testInvalidAuthorizationToken Response status code: 
400]]>
            </line>
            <line>
              <![CDATA[Test Failed: testInvalidAuthorizationToken]]>
            </line>
          </reporter-output>
        </test-method> <!-- testInvalidAuthorizationToken -->
        <test-method signature="testInvalidDateFormat()[pri:0, instance:Ollion.RestAssuredAssignment.badges_ids_GET@2e2ff723]" started-at="2024-02-07T22:11:47 IST" name="testInvalidDateFormat" finished-at="2024-02-07T22:11:49 IST" duration-ms="1260" status="FAIL">
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[expected [200] but found [400]]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: expected [200] but found [400]
at org.testng.Assert.fail(Assert.java:111)
at org.testng.Assert.failNotEquals(Assert.java:1578)
at org.testng.Assert.assertEqualsImpl(Assert.java:150)
at org.testng.Assert.assertEquals(Assert.java:132)
at org.testng.Assert.assertEquals(Assert.java:1419)
at org.testng.Assert.assertEquals(Assert.java:1383)
at org.testng.Assert.assertEquals(Assert.java:1429)
at Ollion.RestAssuredAssignment.badges_ids_GET.testInvalidDateFormat(badges_ids_GET.java:216)
at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:103)
at java.base/java.lang.reflect.Method.invoke(Method.java:580)
at org.testng.internal.invokers.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:139)
at org.testng.internal.invokers.TestInvoker.invokeMethod(TestInvoker.java:664)
at org.testng.internal.invokers.TestInvoker.invokeTestMethod(TestInvoker.java:228)
at org.testng.internal.invokers.MethodRunner.runInSequence(MethodRunner.java:63)
at org.testng.internal.invokers.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:961)
at org.testng.internal.invokers.TestInvoker.invokeTestMethods(TestInvoker.java:201)
at org.testng.internal.invokers.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:148)
at org.testng.internal.invokers.TestMethodWorker.run(TestMethodWorker.java:128)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1596)
at org.testng.TestRunner.privateRun(TestRunner.java:819)
at org.testng.TestRunner.run(TestRunner.java:619)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:443)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:437)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:397)
at org.testng.SuiteRunner.run(SuiteRunner.java:336)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:95)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1301)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1228)
at org.testng.TestNG.runSuites(TestNG.java:1134)
at org.testng.TestNG.run(TestNG.java:1101)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
            <line>
              <![CDATA[Test Started: testInvalidDateFormat]]>
            </line>
            <line>
              <![CDATA[testInvalidDateFormat Response: {
    "error_id": 502,
    "error_message": "too many requests from this IP, more requests available in 19603 seconds",
    "error_name": "throttle_violation"
}]]>
            </line>
            <line>
              <![CDATA[testInvalidDateFormat Response status code: 400]]>
            </line>
            <line>
              <![CDATA[Test Failed: testInvalidDateFormat]]>
            </line>
          </reporter-output>
        </test-method> <!-- testInvalidDateFormat -->
        <test-method signature="testInvalidID()[pri:0, instance:Ollion.RestAssuredAssignment.badges_ids_GET@2e2ff723]" started-at="2024-02-07T22:11:49 IST" name="testInvalidID" finished-at="2024-02-07T22:11:54 IST" duration-ms="5485" status="FAIL">
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[expected [404] but found [502]]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: expected [404] but found [502]
at org.testng.Assert.fail(Assert.java:111)
at org.testng.Assert.failNotEquals(Assert.java:1578)
at org.testng.Assert.assertEqualsImpl(Assert.java:150)
at org.testng.Assert.assertEquals(Assert.java:132)
at org.testng.Assert.assertEquals(Assert.java:1419)
at org.testng.Assert.assertEquals(Assert.java:1383)
at org.testng.Assert.assertEquals(Assert.java:1429)
at Ollion.RestAssuredAssignment.badges_ids_GET.testInvalidID(badges_ids_GET.java:317)
at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:103)
at java.base/java.lang.reflect.Method.invoke(Method.java:580)
at org.testng.internal.invokers.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:139)
at org.testng.internal.invokers.TestInvoker.invokeMethod(TestInvoker.java:664)
at org.testng.internal.invokers.TestInvoker.invokeTestMethod(TestInvoker.java:228)
at org.testng.internal.invokers.MethodRunner.runInSequence(MethodRunner.java:63)
at org.testng.internal.invokers.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:961)
at org.testng.internal.invokers.TestInvoker.invokeTestMethods(TestInvoker.java:201)
at org.testng.internal.invokers.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:148)
at org.testng.internal.invokers.TestMethodWorker.run(TestMethodWorker.java:128)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1596)
at org.testng.TestRunner.privateRun(TestRunner.java:819)
at org.testng.TestRunner.run(TestRunner.java:619)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:443)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:437)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:397)
at org.testng.SuiteRunner.run(SuiteRunner.java:336)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:95)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1301)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1228)
at org.testng.TestNG.runSuites(TestNG.java:1134)
at org.testng.TestNG.run(TestNG.java:1101)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
            <line>
              <![CDATA[Test Started: testInvalidID]]>
            </line>
            <line>
              <![CDATA[testInvalidID Response: {
    "error_id": 502,
    "error_message": "too many requests from this IP, more requests available in 19602 seconds",
    "error_name": "throttle_violation"
}]]>
            </line>
            <line>
              <![CDATA[testInvalidID Response status code: 400]]>
            </line>
            <line>
              <![CDATA[testInvalidID Response status code check successful ]]>
            </line>
            <line>
              <![CDATA[Test Failed: testInvalidID]]>
            </line>
          </reporter-output>
        </test-method> <!-- testInvalidID -->
        <test-method signature="testInvalidMinParameter()[pri:0, instance:Ollion.RestAssuredAssignment.badges_ids_GET@2e2ff723]" started-at="2024-02-07T22:11:54 IST" name="testInvalidMinParameter" finished-at="2024-02-07T22:11:56 IST" duration-ms="2040" status="FAIL">
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[expected [400] but found [502]]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: expected [400] but found [502]
at org.testng.Assert.fail(Assert.java:111)
at org.testng.Assert.failNotEquals(Assert.java:1578)
at org.testng.Assert.assertEqualsImpl(Assert.java:150)
at org.testng.Assert.assertEquals(Assert.java:132)
at org.testng.Assert.assertEquals(Assert.java:1419)
at org.testng.Assert.assertEquals(Assert.java:1383)
at org.testng.Assert.assertEquals(Assert.java:1429)
at Ollion.RestAssuredAssignment.badges_ids_GET.testInvalidMinParameter(badges_ids_GET.java:249)
at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:103)
at java.base/java.lang.reflect.Method.invoke(Method.java:580)
at org.testng.internal.invokers.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:139)
at org.testng.internal.invokers.TestInvoker.invokeMethod(TestInvoker.java:664)
at org.testng.internal.invokers.TestInvoker.invokeTestMethod(TestInvoker.java:228)
at org.testng.internal.invokers.MethodRunner.runInSequence(MethodRunner.java:63)
at org.testng.internal.invokers.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:961)
at org.testng.internal.invokers.TestInvoker.invokeTestMethods(TestInvoker.java:201)
at org.testng.internal.invokers.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:148)
at org.testng.internal.invokers.TestMethodWorker.run(TestMethodWorker.java:128)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1596)
at org.testng.TestRunner.privateRun(TestRunner.java:819)
at org.testng.TestRunner.run(TestRunner.java:619)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:443)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:437)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:397)
at org.testng.SuiteRunner.run(SuiteRunner.java:336)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:95)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1301)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1228)
at org.testng.TestNG.runSuites(TestNG.java:1134)
at org.testng.TestNG.run(TestNG.java:1101)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
            <line>
              <![CDATA[Test Started: testInvalidMinParameter]]>
            </line>
            <line>
              <![CDATA[testInvalidMinParameter Response: {
    "error_id": 502,
    "error_message": "too many requests from this IP, more requests available in 19596 seconds",
    "error_name": "throttle_violation"
}]]>
            </line>
            <line>
              <![CDATA[testInvalidMinParameter Response status code: 400]]>
            </line>
            <line>
              <![CDATA[testInvalidMinParameter Response status code check successful ]]>
            </line>
            <line>
              <![CDATA[Test Failed: testInvalidMinParameter]]>
            </line>
          </reporter-output>
        </test-method> <!-- testInvalidMinParameter -->
        <test-method signature="testInvalidOrderParameter()[pri:0, instance:Ollion.RestAssuredAssignment.badges_ids_GET@2e2ff723]" started-at="2024-02-07T22:11:56 IST" name="testInvalidOrderParameter" finished-at="2024-02-07T22:11:58 IST" duration-ms="1692" status="FAIL">
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[expected [400] but found [502]]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: expected [400] but found [502]
at org.testng.Assert.fail(Assert.java:111)
at org.testng.Assert.failNotEquals(Assert.java:1578)
at org.testng.Assert.assertEqualsImpl(Assert.java:150)
at org.testng.Assert.assertEquals(Assert.java:132)
at org.testng.Assert.assertEquals(Assert.java:1419)
at org.testng.Assert.assertEquals(Assert.java:1383)
at org.testng.Assert.assertEquals(Assert.java:1429)
at Ollion.RestAssuredAssignment.badges_ids_GET.testInvalidOrderParameter(badges_ids_GET.java:186)
at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:103)
at java.base/java.lang.reflect.Method.invoke(Method.java:580)
at org.testng.internal.invokers.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:139)
at org.testng.internal.invokers.TestInvoker.invokeMethod(TestInvoker.java:664)
at org.testng.internal.invokers.TestInvoker.invokeTestMethod(TestInvoker.java:228)
at org.testng.internal.invokers.MethodRunner.runInSequence(MethodRunner.java:63)
at org.testng.internal.invokers.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:961)
at org.testng.internal.invokers.TestInvoker.invokeTestMethods(TestInvoker.java:201)
at org.testng.internal.invokers.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:148)
at org.testng.internal.invokers.TestMethodWorker.run(TestMethodWorker.java:128)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1596)
at org.testng.TestRunner.privateRun(TestRunner.java:819)
at org.testng.TestRunner.run(TestRunner.java:619)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:443)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:437)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:397)
at org.testng.SuiteRunner.run(SuiteRunner.java:336)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:95)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1301)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1228)
at org.testng.TestNG.runSuites(TestNG.java:1134)
at org.testng.TestNG.run(TestNG.java:1101)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
            <line>
              <![CDATA[Test Started: testInvalidOrderParameter]]>
            </line>
            <line>
              <![CDATA[testInvalidOrderParameter Response: {
    "error_id": 502,
    "error_message": "too many requests from this IP, more requests available in 19594 seconds",
    "error_name": "throttle_violation"
}]]>
            </line>
            <line>
              <![CDATA[testInvalidOrderParameter Response status code: 400]]>
            </line>
            <line>
              <![CDATA[testInvalidOrderParameter Response status code check successful ]]>
            </line>
            <line>
              <![CDATA[Test Failed: testInvalidOrderParameter]]>
            </line>
          </reporter-output>
        </test-method> <!-- testInvalidOrderParameter -->
        <test-method signature="testInvalidPageNumber()[pri:0, instance:Ollion.RestAssuredAssignment.badges_ids_GET@2e2ff723]" started-at="2024-02-07T22:11:58 IST" name="testInvalidPageNumber" finished-at="2024-02-07T22:11:59 IST" duration-ms="1587" status="FAIL">
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[expected [400] but found [502]]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: expected [400] but found [502]
at org.testng.Assert.fail(Assert.java:111)
at org.testng.Assert.failNotEquals(Assert.java:1578)
at org.testng.Assert.assertEqualsImpl(Assert.java:150)
at org.testng.Assert.assertEquals(Assert.java:132)
at org.testng.Assert.assertEquals(Assert.java:1419)
at org.testng.Assert.assertEquals(Assert.java:1383)
at org.testng.Assert.assertEquals(Assert.java:1429)
at Ollion.RestAssuredAssignment.badges_ids_GET.testInvalidPageNumber(badges_ids_GET.java:123)
at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:103)
at java.base/java.lang.reflect.Method.invoke(Method.java:580)
at org.testng.internal.invokers.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:139)
at org.testng.internal.invokers.TestInvoker.invokeMethod(TestInvoker.java:664)
at org.testng.internal.invokers.TestInvoker.invokeTestMethod(TestInvoker.java:228)
at org.testng.internal.invokers.MethodRunner.runInSequence(MethodRunner.java:63)
at org.testng.internal.invokers.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:961)
at org.testng.internal.invokers.TestInvoker.invokeTestMethods(TestInvoker.java:201)
at org.testng.internal.invokers.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:148)
at org.testng.internal.invokers.TestMethodWorker.run(TestMethodWorker.java:128)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1596)
at org.testng.TestRunner.privateRun(TestRunner.java:819)
at org.testng.TestRunner.run(TestRunner.java:619)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:443)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:437)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:397)
at org.testng.SuiteRunner.run(SuiteRunner.java:336)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:95)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1301)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1228)
at org.testng.TestNG.runSuites(TestNG.java:1134)
at org.testng.TestNG.run(TestNG.java:1101)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
            <line>
              <![CDATA[Test Started: testInvalidPageNumber]]>
            </line>
            <line>
              <![CDATA[testInvalidPageNumber Response: {
    "error_id": 502,
    "error_message": "too many requests from this IP, more requests available in 19592 seconds",
    "error_name": "throttle_violation"
}]]>
            </line>
            <line>
              <![CDATA[testInvalidPageNumber Response status code: 400]]>
            </line>
            <line>
              <![CDATA[testInvalidPageNumber Response status code check successful ]]>
            </line>
            <line>
              <![CDATA[Test Failed: testInvalidPageNumber]]>
            </line>
          </reporter-output>
        </test-method> <!-- testInvalidPageNumber -->
        <test-method signature="testInvalidPageSize()[pri:0, instance:Ollion.RestAssuredAssignment.badges_ids_GET@2e2ff723]" started-at="2024-02-07T22:11:59 IST" name="testInvalidPageSize" finished-at="2024-02-07T22:12:01 IST" duration-ms="1544" status="FAIL">
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[expected [200] but found [400]]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: expected [200] but found [400]
at org.testng.Assert.fail(Assert.java:111)
at org.testng.Assert.failNotEquals(Assert.java:1578)
at org.testng.Assert.assertEqualsImpl(Assert.java:150)
at org.testng.Assert.assertEquals(Assert.java:132)
at org.testng.Assert.assertEquals(Assert.java:1419)
at org.testng.Assert.assertEquals(Assert.java:1383)
at org.testng.Assert.assertEquals(Assert.java:1429)
at Ollion.RestAssuredAssignment.badges_ids_GET.testInvalidPageSize(badges_ids_GET.java:153)
at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:103)
at java.base/java.lang.reflect.Method.invoke(Method.java:580)
at org.testng.internal.invokers.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:139)
at org.testng.internal.invokers.TestInvoker.invokeMethod(TestInvoker.java:664)
at org.testng.internal.invokers.TestInvoker.invokeTestMethod(TestInvoker.java:228)
at org.testng.internal.invokers.MethodRunner.runInSequence(MethodRunner.java:63)
at org.testng.internal.invokers.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:961)
at org.testng.internal.invokers.TestInvoker.invokeTestMethods(TestInvoker.java:201)
at org.testng.internal.invokers.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:148)
at org.testng.internal.invokers.TestMethodWorker.run(TestMethodWorker.java:128)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1596)
at org.testng.TestRunner.privateRun(TestRunner.java:819)
at org.testng.TestRunner.run(TestRunner.java:619)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:443)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:437)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:397)
at org.testng.SuiteRunner.run(SuiteRunner.java:336)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:95)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1301)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1228)
at org.testng.TestNG.runSuites(TestNG.java:1134)
at org.testng.TestNG.run(TestNG.java:1101)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
            <line>
              <![CDATA[Test Started: testInvalidPageSize]]>
            </line>
            <line>
              <![CDATA[testInvalidPageSize Response: {
    "error_id": 502,
    "error_message": "too many requests from this IP, more requests available in 19591 seconds",
    "error_name": "throttle_violation"
}]]>
            </line>
            <line>
              <![CDATA[testInvalidPageSize Response status code: 400]]>
            </line>
            <line>
              <![CDATA[Test Failed: testInvalidPageSize]]>
            </line>
          </reporter-output>
        </test-method> <!-- testInvalidPageSize -->
        <test-method signature="testInvalidSortParameter()[pri:0, instance:Ollion.RestAssuredAssignment.badges_ids_GET@2e2ff723]" started-at="2024-02-07T22:12:01 IST" name="testInvalidSortParameter" finished-at="2024-02-07T22:12:03 IST" duration-ms="1550" status="FAIL">
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[expected [400] but found [502]]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: expected [400] but found [502]
at org.testng.Assert.fail(Assert.java:111)
at org.testng.Assert.failNotEquals(Assert.java:1578)
at org.testng.Assert.assertEqualsImpl(Assert.java:150)
at org.testng.Assert.assertEquals(Assert.java:132)
at org.testng.Assert.assertEquals(Assert.java:1419)
at org.testng.Assert.assertEquals(Assert.java:1383)
at org.testng.Assert.assertEquals(Assert.java:1429)
at Ollion.RestAssuredAssignment.badges_ids_GET.testInvalidSortParameter(badges_ids_GET.java:283)
at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:103)
at java.base/java.lang.reflect.Method.invoke(Method.java:580)
at org.testng.internal.invokers.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:139)
at org.testng.internal.invokers.TestInvoker.invokeMethod(TestInvoker.java:664)
at org.testng.internal.invokers.TestInvoker.invokeTestMethod(TestInvoker.java:228)
at org.testng.internal.invokers.MethodRunner.runInSequence(MethodRunner.java:63)
at org.testng.internal.invokers.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:961)
at org.testng.internal.invokers.TestInvoker.invokeTestMethods(TestInvoker.java:201)
at org.testng.internal.invokers.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:148)
at org.testng.internal.invokers.TestMethodWorker.run(TestMethodWorker.java:128)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1596)
at org.testng.TestRunner.privateRun(TestRunner.java:819)
at org.testng.TestRunner.run(TestRunner.java:619)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:443)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:437)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:397)
at org.testng.SuiteRunner.run(SuiteRunner.java:336)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:95)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1301)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1228)
at org.testng.TestNG.runSuites(TestNG.java:1134)
at org.testng.TestNG.run(TestNG.java:1101)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
            <line>
              <![CDATA[Test Started: testInvalidSortParameter]]>
            </line>
            <line>
              <![CDATA[testInvalidSortParameter Response: {
    "error_id": 502,
    "error_message": "too many requests from this IP, more requests available in 19589 seconds",
    "error_name": "throttle_violation"
}]]>
            </line>
            <line>
              <![CDATA[testInvalidSortParameter Response status code: 400]]>
            </line>
            <line>
              <![CDATA[testInvalidSortParameter Response status code check successful ]]>
            </line>
            <line>
              <![CDATA[Test Failed: testInvalidSortParameter]]>
            </line>
          </reporter-output>
        </test-method> <!-- testInvalidSortParameter -->
        <test-method signature="testMissingRequiredParameters()[pri:0, instance:Ollion.RestAssuredAssignment.badges_ids_GET@2e2ff723]" started-at="2024-02-07T22:12:03 IST" name="testMissingRequiredParameters" finished-at="2024-02-07T22:12:04 IST" duration-ms="1536" status="FAIL">
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[expected [400] but found [502]]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: expected [400] but found [502]
at org.testng.Assert.fail(Assert.java:111)
at org.testng.Assert.failNotEquals(Assert.java:1578)
at org.testng.Assert.assertEqualsImpl(Assert.java:150)
at org.testng.Assert.assertEquals(Assert.java:132)
at org.testng.Assert.assertEquals(Assert.java:1419)
at org.testng.Assert.assertEquals(Assert.java:1383)
at org.testng.Assert.assertEquals(Assert.java:1429)
at Ollion.RestAssuredAssignment.badges_ids_GET.testMissingRequiredParameters(badges_ids_GET.java:344)
at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:103)
at java.base/java.lang.reflect.Method.invoke(Method.java:580)
at org.testng.internal.invokers.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:139)
at org.testng.internal.invokers.TestInvoker.invokeMethod(TestInvoker.java:664)
at org.testng.internal.invokers.TestInvoker.invokeTestMethod(TestInvoker.java:228)
at org.testng.internal.invokers.MethodRunner.runInSequence(MethodRunner.java:63)
at org.testng.internal.invokers.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:961)
at org.testng.internal.invokers.TestInvoker.invokeTestMethods(TestInvoker.java:201)
at org.testng.internal.invokers.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:148)
at org.testng.internal.invokers.TestMethodWorker.run(TestMethodWorker.java:128)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1596)
at org.testng.TestRunner.privateRun(TestRunner.java:819)
at org.testng.TestRunner.run(TestRunner.java:619)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:443)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:437)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:397)
at org.testng.SuiteRunner.run(SuiteRunner.java:336)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:95)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1301)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1228)
at org.testng.TestNG.runSuites(TestNG.java:1134)
at org.testng.TestNG.run(TestNG.java:1101)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
            <line>
              <![CDATA[Test Started: testMissingRequiredParameters]]>
            </line>
            <line>
              <![CDATA[testMissingRequiredParameters Response: {
    "error_id": 502,
    "error_message": "too many requests from this IP, more requests available in 19588 seconds",
    "error_name": "throttle_violation"
}]]>
            </line>
            <line>
              <![CDATA[testMissingRequiredParameters Response status code: 400]]>
            </line>
            <line>
              <![CDATA[testMissingRequiredParameters Schema validation successful. ]]>
            </line>
            <line>
              <![CDATA[testMissingRequiredParameters Response status code check successful ]]>
            </line>
            <line>
              <![CDATA[Test Failed: testMissingRequiredParameters]]>
            </line>
          </reporter-output>
        </test-method> <!-- testMissingRequiredParameters -->
        <test-method signature="testValidRequest()[pri:0, instance:Ollion.RestAssuredAssignment.badges_ids_GET@2e2ff723]" started-at="2024-02-07T22:12:04 IST" name="testValidRequest" finished-at="2024-02-07T22:12:06 IST" duration-ms="1509" status="FAIL">
          <exception class="java.lang.IllegalArgumentException">
            <message>
              <![CDATA[Schema to use cannot be null]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.IllegalArgumentException: Schema to use cannot be null
at io.restassured.module.jsv.JsonSchemaValidator.validateSchemaIsNotNull(JsonSchemaValidator.java:270)
at io.restassured.module.jsv.JsonSchemaValidator.access$300(JsonSchemaValidator.java:75)
at io.restassured.module.jsv.JsonSchemaValidator$JsonSchemaValidatorFactory.create(JsonSchemaValidator.java:281)
at io.restassured.module.jsv.JsonSchemaValidator.matchesJsonSchema(JsonSchemaValidator.java:166)
at io.restassured.module.jsv.JsonSchemaValidator.matchesJsonSchemaInClasspath(JsonSchemaValidator.java:117)
at Ollion.RestAssuredAssignment.badges_ids_GET.testValidRequest(badges_ids_GET.java:46)
at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:103)
at java.base/java.lang.reflect.Method.invoke(Method.java:580)
at org.testng.internal.invokers.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:139)
at org.testng.internal.invokers.TestInvoker.invokeMethod(TestInvoker.java:664)
at org.testng.internal.invokers.TestInvoker.invokeTestMethod(TestInvoker.java:228)
at org.testng.internal.invokers.MethodRunner.runInSequence(MethodRunner.java:63)
at org.testng.internal.invokers.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:961)
at org.testng.internal.invokers.TestInvoker.invokeTestMethods(TestInvoker.java:201)
at org.testng.internal.invokers.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:148)
at org.testng.internal.invokers.TestMethodWorker.run(TestMethodWorker.java:128)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1596)
at org.testng.TestRunner.privateRun(TestRunner.java:819)
at org.testng.TestRunner.run(TestRunner.java:619)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:443)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:437)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:397)
at org.testng.SuiteRunner.run(SuiteRunner.java:336)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:95)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1301)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1228)
at org.testng.TestNG.runSuites(TestNG.java:1134)
at org.testng.TestNG.run(TestNG.java:1101)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.IllegalArgumentException -->
          <reporter-output>
            <line>
              <![CDATA[Test Started: testValidRequest]]>
            </line>
            <line>
              <![CDATA[Test Failed: testValidRequest]]>
            </line>
          </reporter-output>
        </test-method> <!-- testValidRequest -->
      </class> <!-- Ollion.RestAssuredAssignment.badges_ids_GET -->
    </test> <!-- Test -->
  </suite> <!-- Suite -->
</testng-results>
